// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx9XJZ9YuiWshPz3gVMbVCNmb4oNruSwU',
    appId: '1:286540624146:web:222200945a5d282b7983cb',
    messagingSenderId: '286540624146',
    projectId: 'place-mate1',
    authDomain: 'place-mate1.firebaseapp.com',
    storageBucket: 'place-mate1.firebasestorage.app',
    measurementId: 'G-0S23MRJWBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3jehscxsFYCIYROPaxMeyZPByvwyPeeY',
    appId: '1:286540624146:android:0ed6f038680fddc17983cb',
    messagingSenderId: '286540624146',
    projectId: 'place-mate1',
    storageBucket: 'place-mate1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnEFOQCNciGiPrt60qxb-26lhqPYYpno4',
    appId: '1:286540624146:ios:b9c861c41a54d7d97983cb',
    messagingSenderId: '286540624146',
    projectId: 'place-mate1',
    storageBucket: 'place-mate1.firebasestorage.app',
    iosBundleId: 'com.example.placeMate',
  );

}